services:
  postgres:
    image: postgres:17-alpine
    container_name: devnotes-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: sara
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devnotes

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sara -d devnotes"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
